annotations:
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts
  artifacthub.io/maintainers: |
    - name: dacamposol
      email: dacamposol@gmail.com
    - name: desaintmartin
      email: cedric@desaintmartin.fr
    - name: QuentinBisson
      email: quentin.bisson@gmail.com
apiVersion: v2
appVersion: v0.81.0
dependencies:
- name: crds
  repository: ""
  version: 0.0.0
description: 'A Helm chart that collects custom resource definitions (CRDs) from the
  Prometheus Operator, allowing for seamless integration with GitOps tools '
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
keywords:
- prometheus
- crds
kubeVersion: '>=1.16.0-0'
maintainers:
- email: dacamposol@gmail.com
  name: dacamposol
  url: https://github.com/dacamposol
- email: cedric@desaintmartin.fr
  name: desaintmartin
  url: https://github.com/desaintmartin
- email: quentin.bisson@gmail.com
  name: QuentinBisson
  url: https://github.com/QuentinBisson
- email: github@jkroepke.de
  name: Jan-Otto Kr√∂pke
  url: https://github.com/jkroepke
name: prometheus-operator-crds
sources:
- https://github.com/prometheus-community/helm-charts
type: application
version: 19.0.0
